{

    "token": 'wUTO67WZUeJr6sBY-7HJGf_x7eSt-HLz15bpsHLTFysG3QBy2xhTf--KgkmI4Kb3yYm8jaegHgooMN8VkZAXvcPmKO6_drVU0xvPjvKh25sPgT_AT7FMnEd7',
    "study_id": '6619588544ec034de96f30d1',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
