{

    "token": '4J_fnd9ghvgAbDt7cgqokyulmE_g1Cf-LmipcqkBRaZJU08FRiRxTXovpjTTZiInL7EbJSsLMQNL_PwlHob5k8lU00MRzLv79ZvrLSHqpoXrm-uyVHwCWpht',
    "study_id": '662fed6578cfc82c5a994917',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
