{
    "port": 9001,

    "server_name": "potato annotator",

    "annotation_task_name": "Doctor Patient Conversation Analysis",

    # Potato will write the annotation file for all annotations to this
    # directory, as well as per-annotator output files and state information
    # necessary to restart annotation.
    "output_annotation_dir": "annotation_output/",

    # The output format for the all-annotator data. Allowed formats are:
    # * jsonl
    # * json (same output as jsonl)
    # * csv
    # * tsv
    #
    "output_annotation_format": "tsv",

    # If annotators are using a codebook, this will be linked at the top to the
    # instance for easy access
    "annotation_codebook_url": "",

    "surveyflow": {
      "on": True,
    
     "order": [
            "pre_annotation",
            "post_annotation"
        ],

      "pre_annotation": [
        {'file':'surveyflow/instruction.jsonl','text':'Overview of the task'}],
  
      "post_annotation": [
      {'file':'surveyflow/post_annotation_question.jsonl','text':'Post annotation question'}
        ],
      # If set, we will automatically generate testing questions similar to the annotation instances, but explicitly ask the annotator to choose one option
      "testing": [],
    },


    "data_files": [
    
       "data/doctor_patient_convo_data.json"
    ],

    "item_properties": {
        "id_key": "id",
        "text_key": "text",
        # "context_key": "context"
    },


   
    "automatic_assignment": {
      #whether do automatic task assignment for annotators, default False.
      "on": True,
      "output_filename": 'task_assignment.json',
      "sampling_strategy": 'group_random',
      "labels_per_instance": 12,
      "instance_per_annotator": 1,
      "test_question_per_annotator": 0, # you must set up the test question in surveyflow to use this function

      "users": [  ],
    },


    "user_config": {

      "allow_all_users": True,
      
      "users": [  ],
    },

    "login": {
        "type": "url_direct",
        "url_argument": "PROLIFIC_PID"
    },

    #the jumping-to-id function will be disabled if "jumping_to_id_disabled" is True
    "jumping_to_id_disabled": True,

    #the navigation bar will be hidden to the annotators if "hide_navbar" is True
    "hide_navbar": True,

    #list_as_text is used when the input text is actually a list of texts, usually used for best-worst-scaling or dialogue analysis
    "list_as_text": {
      "text_list_prefix_type": 'none', #whether automatically insert a prefix for each line, currently supporting 'number', 'alphabet', 'number'
      "horizontal": True,
    },

    # How many seconds do you want the annotators spend on each instance, after
    # that, an alert will be sent per alert_time_each_instance seconds.
    "alert_time_each_instance": 10000000,

    "annotation_schemes": [
      {
          "annotation_type": "radio",
          "name": "observer_competence",
          "description": "From an observer's POV, how competent do you think the patient sounds?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_competence",
          "description": "From the patient's POV, how competent do you think the doctor views you?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "observer_agency",
          "description": "From an observer's POV, how much agency do you think the patient has?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_agency",
          "description": "From the patient's POV, how much agency do you think the doctor thinks you have?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "observer_communicator",
          "description": "From an observer's POV, how good of a communicator is the patient?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_communicator",
          "description": "From the patient's POV, how good of a communicator do you think the doctor views you?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_respect",
          "description": "From the patient's POV, how respectful is the doctor?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_empathy",
          "description": "From the patient's POV, how empathetic is the doctor?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_warmth",
          "description": "From the patient's POV, how warm is the doctor?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_info",
          "description": "From the patient's POV, how informative is the doctor?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_support",
          "description": "From the patient's POV, how supportive is the doctor?",

          # If true, display the labels horizontally
          "horizontal": True,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

      {
          "annotation_type": "radio",
          "name": "patient_partner",
          "description": "From the patient's POV, how much does the doctor build partnership?",

          # If true, display the labels horizontally
          "horizontal": False,

          "labels": [
             "low", "slightly low", "medium", "slightly high", "high","not applicable"
          ],
          "sequential_key_binding": True,
      },

    ],

    # The html that changes the visualiztation for your task. Change this file
    # to influence the layout and description of your task. This is not a full
    # HTML page, just the piece that does lays out your task's pieces
    # you may use templates in our lib, if you want to use your own template,
    # please replace the string as a path to the template
   
    # "html_layout": "../templates/Doctor-Patient-Conversation-Analysis- copy.html",

    "html_layout": "templates/layout.html",

    # The core UI files for Potato. You should not need to change these normally.
    #
    # Exceptions to this might include: 
    # 1) You want to add custom CSS/fonts to style your task
    # 2) Your layout requires additional JS/assets to render
    # 3) You want to support additional keybinding magic
    #
    # if you want to use your own template,
    # please replace the string as a path to the template
    # "base_html_template": "../../potato/templates/Doctor-Patient-Conversation-Analysis-base_template.html",
    # "base_html_template": "../templates/Dialogue-Analysis-Dialogue-Analysis-base_template copy.html",
    "base_html_template": "default",
    "header_file": "default",

    # This is where the actual HTML files will be generated
    "site_dir": "default",

}