{

    "token": 'sa_ttwyHn8MQjNvbFBmmASchY4a-ggBU9532bWArkfLDXts9tYyDJj7fPULqp-Kl9xkAp2MAACB77RuNwX78jv_bApbEXos0mwp4ZPB1H_WyNELxvDMsK8-P',
    "study_id": '661582568b65b815de011903',

    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
