{

    "token": 'TDWCCWnqoE0cne4QIa_HalfPCVrbYn5LyzNtm9-TA8z2hS1200UFIvU8QZNbwOyw_WOqN84LHQ3-mWX_lYAZmKj3K_ALsjodfRjVcWMLRuo61ydcZ5wTmREq',
    "study_id": '66464b3dc19149614012c8a8',
    "max_concurrent_sessions": 30,
    "workload_checker_period": 300
}
